spring.application.name=ecommerce
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java
server.port=8090

# ── Database ──────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA ───────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── JWT ───────────────────────────────────────────
jwt.secret=thisIsAVeryLongSecretKeyForJWTThatMustBe256BitsLong!
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000

# ── Email ─────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mhalamin04@gmail.com
spring.mail.password=omnu uvnj sztu qhik
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=mhalamin04@gmail.com